on:
  push:
    branches: [ main, overture ]

jobs:

  hello-world:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:

          - release: buster
            date: 20210507
            body: lite
            url-armhf: http://imrc.noip.me/data/2021-05-07-raspios-buster-armhf-lite.zip
            url-arm64: http://imrc.noip.me/data/2021-05-07-raspios-buster-arm64-lite.zip

    env:
      IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/raspberry-pi-os:${{ matrix.release }}-${{ matrix.date }}-${{ matrix.body }}

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate armhf image
        if: ${{ matrix.url-armhf != '' }}
        run: |
          bash generate-root.bash "$IMAGE-armhf" '${{ matrix.url-armhf }}'
          #docker push "$IMAGE-armhf"
      - name: Generate arm64 image
        if: ${{ matrix.url-arm64 != '' }}
        run: |
          bash generate-root.bash "$IMAGE-arm64" '${{ matrix.url-arm64 }}'
          #docker push "$IMAGE-arm64"
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/arm/v6,linux/arm64/v8
          push: true
          tags: $IMAGE
      - name: Merge images
        run: |
          set -x
          [ -n '${{ matrix.url-armhf }}' ] && do_armhf=1
          [ -n '${{ matrix.url-arm64 }}' ] && do_arm64=1
          #docker manifest create "$IMAGE" $([ -n "$do_armhf" ] && echo "$IMAGE-armhf") $([ -n "$do_arm64" ] && echo "$IMAGE-arm64")
          #[ -n "$do_armhf" ] && docker manifest annotate "$IMAGE" "$IMAGE-armhf" --os linux --arch arm --variant v6
          #[ -n "$do_arm64" ] && docker manifest annotate "$IMAGE" "$IMAGE-arm64" --os linux --arch arm64 --variant v8
          #docker manifest push --purge "$IMAGE"
