on:
  push:
    branches: [ main, overture ]

jobs:

  hello-world:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - release: buster
          - body: lite
          - date: 20210507
          - platform: linux/arm/v6
          - url: https://downloads.raspberrypi.org/raspios_lite_armhf/images/raspios_lite_armhf-2021-05-28/2021-05-07-raspios-buster-armhf-lite.zip
        include:
          - release: buster
          - body: lite
          - date: 20210507
          - platform: linux/arm64/v8
          - url: https://downloads.raspberrypi.org/raspios_lite_arm64/images/raspios_lite_arm64-2021-05-28/2021-05-07-raspios-buster-arm64-lite.zip
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate root image
        run: bash generate-root.bash '${{ matrix.url }}'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: ${{ matrix.platform }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/raspberry-pi-os:${{ matrix.date }}
